name: Deploy to EC2 (Build on EC2)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "---- Setting AWS environment ----"
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}

            echo "---- Pulling latest code ----"

            # Clone or update repo in ~/queue_model
            if [ ! -d ~/queue_model ]; then
              git clone https://github.com/uctconsulting12/queue_model.git ~/queue_model
            else
              cd ~/queue_model
              git pull origin main
            fi

            echo "---- Building Docker image ----"
            cd ~/queue_model
            sudo docker build -t qeue_image .
            echo "--- remove none images ------"
            sudo docker image prune -f

            echo "---- Stopping old container ----"
            sudo docker stop queue_container || true
            sudo docker rm queue_container || true

            echo "---- Running new container with AWS creds ----"
            sudo docker run -d \
            --name queue_container \
            -p 8001:8001 \
            --gpus all \
            -v "$HOME/.aws:/root/.aws"
            queue_image

            echo "Deployment completed. "
